# from elo import compare
from player import Player
from team import Team


p1 = Player('Marcos')
p2 = Player('Raoni')
p3 = Player('Renato')
p4 = Player('Caio')
p5 = Player('Altamir')
p6 = Player('Mickael')
p7 = Player('Felipe')
t1 = Team('t', [p1, p2, p3])

p5.compare_defense(p1, 1)
p2.compare_defense(p3, 1)
p2.compare_defense(p1, 1)
p7.compare_defense(p1, 1)
p6.compare_defense(p6, 1)
p5.compare_defense(p6, 1)
p3.compare_defense(p4, 1)
p4.compare_defense(p3, 1)
p1.compare_defense(p5, 1)
p6.compare_defense(p7, 1)
p3.compare_defense(p7, 1)
p2.compare_defense(p3, 1)
p2.compare_defense(p4, 1)
p2.compare_defense(p7, 1)
p6.compare_defense(p5, 1)
p4.compare_defense(p6, 1)
p5.compare_defense(p6, 1)
p3.compare_defense(p4, 1)
p1.compare_defense(p3, 1)
p4.compare_defense(p1, 1)
p1.compare_defense(p3, 1)
p2.compare_defense(p4, 1)
p6.compare_defense(p4, 1)
p4.compare_defense(p2, 1)
p6.compare_defense(p7, 1)
p2.compare_defense(p2, 1)
p7.compare_defense(p5, 1)
p6.compare_defense(p6, 1)
p7.compare_defense(p6, 1)
p3.compare_defense(p1, 1)
p2.compare_defense(p7, 1)
p7.compare_defense(p3, 1)
p6.compare_defense(p3, 1)
p4.compare_defense(p3, 1)
p2.compare_defense(p6, 1)
p2.compare_defense(p6, 1)
p4.compare_defense(p4, 1)
p2.compare_defense(p1, 1)
p3.compare_defense(p3, 1)
p2.compare_defense(p6, 1)
p1.compare_defense(p6, 1)
p7.compare_defense(p5, 1)
p6.compare_defense(p3, 1)
p5.compare_defense(p6, 1)
p3.compare_defense(p3, 1)
p4.compare_defense(p1, 1)
p6.compare_defense(p5, 1)
p6.compare_defense(p2, 1)
p2.compare_defense(p4, 1)
p1.compare_defense(p1, 1)
p7.compare_defense(p2, 1)
p4.compare_defense(p1, 1)
p5.compare_defense(p4, 1)
p2.compare_defense(p6, 1)
p1.compare_defense(p2, 1)
p6.compare_defense(p3, 1)
p6.compare_defense(p7, 1)
p2.compare_defense(p2, 1)
p6.compare_defense(p7, 1)
p3.compare_defense(p5, 1)
p4.compare_defense(p5, 1)
p4.compare_defense(p7, 1)
p7.compare_defense(p6, 1)
p7.compare_defense(p4, 1)
p7.compare_defense(p2, 1)
p7.compare_defense(p4, 1)
p3.compare_defense(p6, 1)

print('new score p1(' + p1.name + '): ' + str(p1.defense))
print('new score p2(' + p2.name + '): ' + str(p2.defense))
print('new score p3(' + p3.name + '): ' + str(p3.defense))
print('new score p4(' + p4.name + '): ' + str(p4.defense))
print('new score p5(' + p5.name + '): ' + str(p5.defense))
print('new score p6(' + p6.name + '): ' + str(p6.defense))
print('new score p7(' + p7.name + '): ' + str(p7.defense))

print('total: ' + str(p1.defense + p2.defense + p3.defense + p4.defense +
                      p5.defense + p6.defense + p7.defense))

# player

# print (compare(1000, 1000, 1))
